/*Data for country_master*/
insert into `country_master` (`id`, `name`, `ISO`) values('1001','Afghanistan','AF');
insert into `country_master` (`id`, `name`, `ISO`) values('1002','Albania','AL');
insert into `country_master` (`id`, `name`, `ISO`) values('1003','Algeria','DZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1004','American Samoa','AS');
insert into `country_master` (`id`, `name`, `ISO`) values('1005','Andorra','AD');
insert into `country_master` (`id`, `name`, `ISO`) values('1006','Angola','AO');
insert into `country_master` (`id`, `name`, `ISO`) values('1007','Anguilla','AI');
insert into `country_master` (`id`, `name`, `ISO`) values('1008','Antarctica','AQ');
insert into `country_master` (`id`, `name`, `ISO`) values('1009','Antigua And Barbuda','AG');
insert into `country_master` (`id`, `name`, `ISO`) values('1010','Argentina','AR');
insert into `country_master` (`id`, `name`, `ISO`) values('1011','Armenia','AM');
insert into `country_master` (`id`, `name`, `ISO`) values('1012','Aruba','AW');
insert into `country_master` (`id`, `name`, `ISO`) values('1013','Australia','AU');
insert into `country_master` (`id`, `name`, `ISO`) values('1014','Austria','AT');
insert into `country_master` (`id`, `name`, `ISO`) values('1015','Azerbaijan','AZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1016','Bahamas','BS');
insert into `country_master` (`id`, `name`, `ISO`) values('1017','Bahrain','BH');
insert into `country_master` (`id`, `name`, `ISO`) values('1018','Bangladesh','BD');
insert into `country_master` (`id`, `name`, `ISO`) values('1019','Barbados','BB');
insert into `country_master` (`id`, `name`, `ISO`) values('1020','Belarus','BY');
insert into `country_master` (`id`, `name`, `ISO`) values('1021','Belgium','BE');
insert into `country_master` (`id`, `name`, `ISO`) values('1022','Belize','BZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1023','Benin','BJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1024','Bermuda','BM');
insert into `country_master` (`id`, `name`, `ISO`) values('1025','Bhutan','BT');
insert into `country_master` (`id`, `name`, `ISO`) values('1026','Bolivia','BO');
insert into `country_master` (`id`, `name`, `ISO`) values('1027','Bosnia and Herzegovina','BA');
insert into `country_master` (`id`, `name`, `ISO`) values('1028','Botswana','BW');
insert into `country_master` (`id`, `name`, `ISO`) values('1029','Bouvet Island','BV');
insert into `country_master` (`id`, `name`, `ISO`) values('1030','Brazil','BR');
insert into `country_master` (`id`, `name`, `ISO`) values('1031','British Indian Ocean Territory','IO');
insert into `country_master` (`id`, `name`, `ISO`) values('1032','Brunei Darussalam','BN');
insert into `country_master` (`id`, `name`, `ISO`) values('1033','Bulgaria','BG');
insert into `country_master` (`id`, `name`, `ISO`) values('1034','Burkina Faso','BF');
insert into `country_master` (`id`, `name`, `ISO`) values('1035','Burundi','BI');
insert into `country_master` (`id`, `name`, `ISO`) values('1036','Cambodia','KH');
insert into `country_master` (`id`, `name`, `ISO`) values('1037','Cameroon','CM');
insert into `country_master` (`id`, `name`, `ISO`) values('1038','Canada','CA');
insert into `country_master` (`id`, `name`, `ISO`) values('1039','Cape Verde','CV');
insert into `country_master` (`id`, `name`, `ISO`) values('1040','Cayman Islands','KY');
insert into `country_master` (`id`, `name`, `ISO`) values('1041','Central African Republic','CF');
insert into `country_master` (`id`, `name`, `ISO`) values('1042','Chad','TD');
insert into `country_master` (`id`, `name`, `ISO`) values('1043','Chile','CL');
insert into `country_master` (`id`, `name`, `ISO`) values('1044','China','CN');
insert into `country_master` (`id`, `name`, `ISO`) values('1045','Christmas Island','CX');
insert into `country_master` (`id`, `name`, `ISO`) values('1046','Cocos (Keeling) Islands','CC');
insert into `country_master` (`id`, `name`, `ISO`) values('1047','Colombia','CO');
insert into `country_master` (`id`, `name`, `ISO`) values('1048','Comoros','KM');
insert into `country_master` (`id`, `name`, `ISO`) values('1049','Congo','CG');
insert into `country_master` (`id`, `name`, `ISO`) values('1050','Congo, Democratic Republic Of The','CD');
insert into `country_master` (`id`, `name`, `ISO`) values('1051','Cook Islands','CK');
insert into `country_master` (`id`, `name`, `ISO`) values('1052','Costa Rica','CR');
insert into `country_master` (`id`, `name`, `ISO`) values('1053','Cote D\'Ivoire (Ivory Coast)','CI');
insert into `country_master` (`id`, `name`, `ISO`) values('1054','Croatia (Hrvatska)','HR');
insert into `country_master` (`id`, `name`, `ISO`) values('1055','Cuba','CU');
insert into `country_master` (`id`, `name`, `ISO`) values('1056','Cyprus','CY');
insert into `country_master` (`id`, `name`, `ISO`) values('1057','Czech Republic','CZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1058','Denmark','DK');
insert into `country_master` (`id`, `name`, `ISO`) values('1059','Djibouti','DJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1060','Dominica','DM');
insert into `country_master` (`id`, `name`, `ISO`) values('1061','Dominican Republic','DO');
insert into `country_master` (`id`, `name`, `ISO`) values('1062','East Timor','TP');
insert into `country_master` (`id`, `name`, `ISO`) values('1063','Ecuador','EC');
insert into `country_master` (`id`, `name`, `ISO`) values('1064','Egypt','EG');
insert into `country_master` (`id`, `name`, `ISO`) values('1065','El Salvador','SV');
insert into `country_master` (`id`, `name`, `ISO`) values('1066','Equatorial Guinea','GQ');
insert into `country_master` (`id`, `name`, `ISO`) values('1067','Eritrea','ER');
insert into `country_master` (`id`, `name`, `ISO`) values('1068','Estonia','EE');
insert into `country_master` (`id`, `name`, `ISO`) values('1069','Ethiopia','ET');
insert into `country_master` (`id`, `name`, `ISO`) values('1070','External Territories of Australia','XA');
insert into `country_master` (`id`, `name`, `ISO`) values('1071','Falkland Islands (Malvinas)','FK');
insert into `country_master` (`id`, `name`, `ISO`) values('1072','Faroe Islands','FO');
insert into `country_master` (`id`, `name`, `ISO`) values('1073','Fiji Islands','FJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1074','Finland','FI');
insert into `country_master` (`id`, `name`, `ISO`) values('1075','France','FR');
insert into `country_master` (`id`, `name`, `ISO`) values('1076','French Guiana','GF');
insert into `country_master` (`id`, `name`, `ISO`) values('1077','French Polynesia','PF');
insert into `country_master` (`id`, `name`, `ISO`) values('1078','French Southern Territories','TF');
insert into `country_master` (`id`, `name`, `ISO`) values('1079','Gabon','GA');
insert into `country_master` (`id`, `name`, `ISO`) values('1080','Gambia','GM');
insert into `country_master` (`id`, `name`, `ISO`) values('1081','Georgia','GE');
insert into `country_master` (`id`, `name`, `ISO`) values('1082','Germany','DE');
insert into `country_master` (`id`, `name`, `ISO`) values('1083','Ghana','GH');
insert into `country_master` (`id`, `name`, `ISO`) values('1084','Gibraltar','GI');
insert into `country_master` (`id`, `name`, `ISO`) values('1085','Greece','GR');
insert into `country_master` (`id`, `name`, `ISO`) values('1086','Greenland','GL');
insert into `country_master` (`id`, `name`, `ISO`) values('1087','Grenada','GD');
insert into `country_master` (`id`, `name`, `ISO`) values('1088','Guadeloupe','GP');
insert into `country_master` (`id`, `name`, `ISO`) values('1089','Guam','GU');
insert into `country_master` (`id`, `name`, `ISO`) values('1090','Guatemala','GT');
insert into `country_master` (`id`, `name`, `ISO`) values('1091','Guernsey and Alderney','XU');
insert into `country_master` (`id`, `name`, `ISO`) values('1092','Guinea','GN');
insert into `country_master` (`id`, `name`, `ISO`) values('1093','Guinea-Bissau','GW');
insert into `country_master` (`id`, `name`, `ISO`) values('1094','Guyana','GY');
insert into `country_master` (`id`, `name`, `ISO`) values('1095','Haiti','HT');
insert into `country_master` (`id`, `name`, `ISO`) values('1096','Heard Island and Mcdonald Islands','HM');
insert into `country_master` (`id`, `name`, `ISO`) values('1097','Honduras','HN');
insert into `country_master` (`id`, `name`, `ISO`) values('1098','Hong Kong','HK');
insert into `country_master` (`id`, `name`, `ISO`) values('1099','Hungary','HU');
insert into `country_master` (`id`, `name`, `ISO`) values('1100','Iceland','IS');
insert into `country_master` (`id`, `name`, `ISO`) values('1101','India','IN');
insert into `country_master` (`id`, `name`, `ISO`) values('1102','Indonesia','ID');
insert into `country_master` (`id`, `name`, `ISO`) values('1103','Iran  Islamic Republic of','IR');
insert into `country_master` (`id`, `name`, `ISO`) values('1104','Iraq','IQ');
insert into `country_master` (`id`, `name`, `ISO`) values('1105','Ireland','IE');
insert into `country_master` (`id`, `name`, `ISO`) values('1106','Israel','IL');
insert into `country_master` (`id`, `name`, `ISO`) values('1107','Italy','IT');
insert into `country_master` (`id`, `name`, `ISO`) values('1108','Jamaica','JM');
insert into `country_master` (`id`, `name`, `ISO`) values('1109','Japan','JP');
insert into `country_master` (`id`, `name`, `ISO`) values('1110','Jersey','XJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1111','Jordan','JO');
insert into `country_master` (`id`, `name`, `ISO`) values('1112','Kazakhstan','KZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1113','Kenya','KE');
insert into `country_master` (`id`, `name`, `ISO`) values('1114','Kiribati','KI');
insert into `country_master` (`id`, `name`, `ISO`) values('1115','Korea, North','KP');
insert into `country_master` (`id`, `name`, `ISO`) values('1116','Korea, South','KR');
insert into `country_master` (`id`, `name`, `ISO`) values('1117','Kuwait','KW');
insert into `country_master` (`id`, `name`, `ISO`) values('1118','Kyrgyzstan','KG');
insert into `country_master` (`id`, `name`, `ISO`) values('1119','Lao Peoples Democratic Republic','LA');
insert into `country_master` (`id`, `name`, `ISO`) values('1120','Latvia','LV');
insert into `country_master` (`id`, `name`, `ISO`) values('1121','Lebanon','LB');
insert into `country_master` (`id`, `name`, `ISO`) values('1122','Lesotho','LS');
insert into `country_master` (`id`, `name`, `ISO`) values('1123','Liberia','LR');
insert into `country_master` (`id`, `name`, `ISO`) values('1124','Libyan Arab Jamahiriya','LY');
insert into `country_master` (`id`, `name`, `ISO`) values('1125','Liechtenstein','LI');
insert into `country_master` (`id`, `name`, `ISO`) values('1126','Lithuania','LT');
insert into `country_master` (`id`, `name`, `ISO`) values('1127','Luxembourg','LU');
insert into `country_master` (`id`, `name`, `ISO`) values('1128','Macao','MO');
insert into `country_master` (`id`, `name`, `ISO`) values('1129','Macedonia  the Former Yugoslav Republic of','MK');
insert into `country_master` (`id`, `name`, `ISO`) values('1130','Madagascar','MG');
insert into `country_master` (`id`, `name`, `ISO`) values('1131','Malawi','MW');
insert into `country_master` (`id`, `name`, `ISO`) values('1132','Malaysia','MY');
insert into `country_master` (`id`, `name`, `ISO`) values('1133','Maldives','MV');
insert into `country_master` (`id`, `name`, `ISO`) values('1134','Mali','ML');
insert into `country_master` (`id`, `name`, `ISO`) values('1135','Malta','MT');
insert into `country_master` (`id`, `name`, `ISO`) values('1136','Man (Isle of)','XM');
insert into `country_master` (`id`, `name`, `ISO`) values('1137','Marshall Islands','MH');
insert into `country_master` (`id`, `name`, `ISO`) values('1138','Martinique','MQ');
insert into `country_master` (`id`, `name`, `ISO`) values('1139','Mauritania','MR');
insert into `country_master` (`id`, `name`, `ISO`) values('1140','Mauritius','MU');
insert into `country_master` (`id`, `name`, `ISO`) values('1141','Mayotte','YT');
insert into `country_master` (`id`, `name`, `ISO`) values('1142','Mexico','MX');
insert into `country_master` (`id`, `name`, `ISO`) values('1143','Micronesia  Federated States of','FM');
insert into `country_master` (`id`, `name`, `ISO`) values('1144','Moldova  Republic of','MD');
insert into `country_master` (`id`, `name`, `ISO`) values('1145','Monaco','MC');
insert into `country_master` (`id`, `name`, `ISO`) values('1146','Mongolia','MN');
insert into `country_master` (`id`, `name`, `ISO`) values('1147','Montserrat','MS');
insert into `country_master` (`id`, `name`, `ISO`) values('1148','Morocco','MA');
insert into `country_master` (`id`, `name`, `ISO`) values('1149','Mozambique','MZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1150','Myanmar','MM');
insert into `country_master` (`id`, `name`, `ISO`) values('1151','Namibia','NA');
insert into `country_master` (`id`, `name`, `ISO`) values('1152','Nauru','NR');
insert into `country_master` (`id`, `name`, `ISO`) values('1153','Nepal','NP');
insert into `country_master` (`id`, `name`, `ISO`) values('1154','Netherlands Antilles','AN');
insert into `country_master` (`id`, `name`, `ISO`) values('1155','Netherlands','NL');
insert into `country_master` (`id`, `name`, `ISO`) values('1156','New Caledonia','NC');
insert into `country_master` (`id`, `name`, `ISO`) values('1157','New Zealand','NZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1158','Nicaragua','NI');
insert into `country_master` (`id`, `name`, `ISO`) values('1159','Niger','NE');
insert into `country_master` (`id`, `name`, `ISO`) values('1160','Nigeria','NG');
insert into `country_master` (`id`, `name`, `ISO`) values('1161','Niue','NU');
insert into `country_master` (`id`, `name`, `ISO`) values('1162','Norfolk Island','NF');
insert into `country_master` (`id`, `name`, `ISO`) values('1163','Northern Mariana Islands','MP');
insert into `country_master` (`id`, `name`, `ISO`) values('1164','Norway','NO');
insert into `country_master` (`id`, `name`, `ISO`) values('1165','Oman','OM');
insert into `country_master` (`id`, `name`, `ISO`) values('1166','Pakistan','PK');
insert into `country_master` (`id`, `name`, `ISO`) values('1167','Palau','PW');
insert into `country_master` (`id`, `name`, `ISO`) values('1168','Palestinian Territory Occupied','PS');
insert into `country_master` (`id`, `name`, `ISO`) values('1169','Panama','PA');
insert into `country_master` (`id`, `name`, `ISO`) values('1170','Papua new Guinea','PG');
insert into `country_master` (`id`, `name`, `ISO`) values('1171','Paraguay','PY');
insert into `country_master` (`id`, `name`, `ISO`) values('1172','Peru','PE');
insert into `country_master` (`id`, `name`, `ISO`) values('1173','Philippines','PH');
insert into `country_master` (`id`, `name`, `ISO`) values('1174','Pitcairn','PN');
insert into `country_master` (`id`, `name`, `ISO`) values('1175','Poland','PL');
insert into `country_master` (`id`, `name`, `ISO`) values('1176','Portugal','PT');
insert into `country_master` (`id`, `name`, `ISO`) values('1177','Puerto Rico','PR');
insert into `country_master` (`id`, `name`, `ISO`) values('1178','Qatar','QA');
insert into `country_master` (`id`, `name`, `ISO`) values('1179','Reunion','RE');
insert into `country_master` (`id`, `name`, `ISO`) values('1180','Romania','RO');
insert into `country_master` (`id`, `name`, `ISO`) values('1181','Russia','RU');
insert into `country_master` (`id`, `name`, `ISO`) values('1182','Rwanda','RW');
insert into `country_master` (`id`, `name`, `ISO`) values('1183','Saint Helena','SH');
insert into `country_master` (`id`, `name`, `ISO`) values('1184','Saint Kitts And Nevis','KN');
insert into `country_master` (`id`, `name`, `ISO`) values('1185','Saint Lucia','LC');
insert into `country_master` (`id`, `name`, `ISO`) values('1186','Saint Pierre and Miquelon','PM');
insert into `country_master` (`id`, `name`, `ISO`) values('1187','Saint Vincent And The Grenadines','VC');
insert into `country_master` (`id`, `name`, `ISO`) values('1188','Samoa','WS');
insert into `country_master` (`id`, `name`, `ISO`) values('1189','San Marino','SM');
insert into `country_master` (`id`, `name`, `ISO`) values('1190','Sao Tome and Principe','ST');
insert into `country_master` (`id`, `name`, `ISO`) values('1191','Saudi Arabia','SA');
insert into `country_master` (`id`, `name`, `ISO`) values('1192','Senegal','SN');
insert into `country_master` (`id`, `name`, `ISO`) values('1193','Serbia and Montenegro','RS');
insert into `country_master` (`id`, `name`, `ISO`) values('1194','Seychelles','SC');
insert into `country_master` (`id`, `name`, `ISO`) values('1195','Sierra Leone','SL');
insert into `country_master` (`id`, `name`, `ISO`) values('1196','Singapore','SG');
insert into `country_master` (`id`, `name`, `ISO`) values('1197','Slovakia','SK');
insert into `country_master` (`id`, `name`, `ISO`) values('1198','Slovenia','SI');
insert into `country_master` (`id`, `name`, `ISO`) values('1199','Smaller Territories of the UK','XG');
insert into `country_master` (`id`, `name`, `ISO`) values('1200','Solomon Islands','SB');
insert into `country_master` (`id`, `name`, `ISO`) values('1201','Somalia','SO');
insert into `country_master` (`id`, `name`, `ISO`) values('1202','South Africa','ZA');
insert into `country_master` (`id`, `name`, `ISO`) values('1203','South Georgia and the South Sandwich Islands','GS');
insert into `country_master` (`id`, `name`, `ISO`) values('1204','South Sudan','SS');
insert into `country_master` (`id`, `name`, `ISO`) values('1205','Spain','ES');
insert into `country_master` (`id`, `name`, `ISO`) values('1206','Sri Lanka','LK');
insert into `country_master` (`id`, `name`, `ISO`) values('1207','Sudan','SD');
insert into `country_master` (`id`, `name`, `ISO`) values('1208','Suriname','SR');
insert into `country_master` (`id`, `name`, `ISO`) values('1209','Svalbard and Jan Mayen','SJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1210','Swaziland','SZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1211','Sweden','SE');
insert into `country_master` (`id`, `name`, `ISO`) values('1212','Switzerland','CH');
insert into `country_master` (`id`, `name`, `ISO`) values('1213','Syria','SY');
insert into `country_master` (`id`, `name`, `ISO`) values('1214','Taiwan','TW');
insert into `country_master` (`id`, `name`, `ISO`) values('1215','Tajikistan','TJ');
insert into `country_master` (`id`, `name`, `ISO`) values('1216','Tanzania','TZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1217','Thailand','TH');
insert into `country_master` (`id`, `name`, `ISO`) values('1218','Togo','TG');
insert into `country_master` (`id`, `name`, `ISO`) values('1219','Tokelau','TK');
insert into `country_master` (`id`, `name`, `ISO`) values('1220','Tonga','TO');
insert into `country_master` (`id`, `name`, `ISO`) values('1221','Trinidad And Tobago','TT');
insert into `country_master` (`id`, `name`, `ISO`) values('1222','Tunisia','TN');
insert into `country_master` (`id`, `name`, `ISO`) values('1223','Turkey','TR');
insert into `country_master` (`id`, `name`, `ISO`) values('1224','Turkmenistan','TM');
insert into `country_master` (`id`, `name`, `ISO`) values('1225','Turks And Caicos Islands','TC');
insert into `country_master` (`id`, `name`, `ISO`) values('1226','Tuvalu','TV');
insert into `country_master` (`id`, `name`, `ISO`) values('1227','Uganda','UG');
insert into `country_master` (`id`, `name`, `ISO`) values('1228','Ukraine','UA');
insert into `country_master` (`id`, `name`, `ISO`) values('1229','United Arab Emirates','AE');
insert into `country_master` (`id`, `name`, `ISO`) values('1230','United Kingdom','GB');
insert into `country_master` (`id`, `name`, `ISO`) values('1231','USA','US');
insert into `country_master` (`id`, `name`, `ISO`) values('1232','United States Minor Outlying Islands','UM');
insert into `country_master` (`id`, `name`, `ISO`) values('1233','Uruguay','UY');
insert into `country_master` (`id`, `name`, `ISO`) values('1234','Uzbekistan','UZ');
insert into `country_master` (`id`, `name`, `ISO`) values('1235','Vanuatu','VU');
insert into `country_master` (`id`, `name`, `ISO`) values('1236','Holy See (Vatican City State)','VA');
insert into `country_master` (`id`, `name`, `ISO`) values('1237','Venezuela','VE');
insert into `country_master` (`id`, `name`, `ISO`) values('1238','Vietnam','VN');
insert into `country_master` (`id`, `name`, `ISO`) values('1239','Virgin Islands (British)','VG');
insert into `country_master` (`id`, `name`, `ISO`) values('1240','Virgin Islands (US)','VI');
insert into `country_master` (`id`, `name`, `ISO`) values('1241','Wallis And Futuna Islands','WF');
insert into `country_master` (`id`, `name`, `ISO`) values('1242','Western Sahara','EH');
insert into `country_master` (`id`, `name`, `ISO`) values('1243','Yemen','YE');
insert into `country_master` (`id`, `name`, `ISO`) values('1244','Yugoslavia','YU');
insert into `country_master` (`id`, `name`, `ISO`) values('1245','Zambia','ZM');
insert into `country_master` (`id`, `name`, `ISO`) values('1246','Zimbabwe','ZW');
insert into `country_master` (`id`, `name`, `ISO`) values('1247','Curacao','CW');
insert into `country_master` (`id`, `name`, `ISO`) values('1248','Aland Islands','AX');
insert into `country_master` (`id`, `name`, `ISO`) values('1249','Saint Barthélemy','BL');
insert into `country_master` (`id`, `name`, `ISO`) values('1250','Bonaire, Sint Eustatius and Saba','BQ');
insert into `country_master` (`id`, `name`, `ISO`) values('1251','Guernsey','GG');
insert into `country_master` (`id`, `name`, `ISO`) values('1252','Isle of Man','IM');
insert into `country_master` (`id`, `name`, `ISO`) values('1253','Jersey','JE');
insert into `country_master` (`id`, `name`, `ISO`) values('1254','Montenegro','ME');
insert into `country_master` (`id`, `name`, `ISO`) values('1255','Saint Martin (french part)','MF');
insert into `country_master` (`id`, `name`, `ISO`) values('1256','Sint Maarten (dutch part)','SX');
insert into `country_master` (`id`, `name`, `ISO`) values('1257','Timor-leste','TL');