insert into `timezone_master` (`id`, `name`, `code`) values('2001','International Date Line West','Etc/GMT+12');
insert into `timezone_master` (`id`, `name`, `code`) values('2002','Midway Island, Samoa','Etc/GMT+11');
insert into `timezone_master` (`id`, `name`, `code`) values('2003','Hawaii Time','US/Hawaii');
insert into `timezone_master` (`id`, `name`, `code`) values('2004','Alaska Time','US/Alaska');
insert into `timezone_master` (`id`, `name`, `code`) values('2005','Pacific Time (US & Canada)','US/Pacific');
insert into `timezone_master` (`id`, `name`, `code`) values('2006','Arizona Time','US/Arizona');
insert into `timezone_master` (`id`, `name`, `code`) values('2007','Chihuahua, La Paz, Mazatlan','America/Chihuahua');
insert into `timezone_master` (`id`, `name`, `code`) values('2008','Mountain Time (US & Canada)','US/Mountain');
insert into `timezone_master` (`id`, `name`, `code`) values('2009','Central America','US/Central');
insert into `timezone_master` (`id`, `name`, `code`) values('2010','Central Time (US & Canada)','US/Central');
insert into `timezone_master` (`id`, `name`, `code`) values('2011','Guadalajara, Mexico City, Monterrey','America/Monterrey');
insert into `timezone_master` (`id`, `name`, `code`) values('2012','Saskatchewan','Canada/Saskatchewan');
insert into `timezone_master` (`id`, `name`, `code`) values('2013','Bogota, Lima, Quito','America/Bogota');
insert into `timezone_master` (`id`, `name`, `code`) values('2014','Eastern Time (US & Canada)','US/Eastern');
insert into `timezone_master` (`id`, `name`, `code`) values('2015','Indiana (East)','US/Eastern');
insert into `timezone_master` (`id`, `name`, `code`) values('2016','Atlantic Time (Canada)','Canada/Atlantic');
insert into `timezone_master` (`id`, `name`, `code`) values('2017','Caracas, La Paz','America/Caracas');
insert into `timezone_master` (`id`, `name`, `code`) values('2018','Santiago','America/Santiago');
insert into `timezone_master` (`id`, `name`, `code`) values('2019','Newfoundland','Canada/Newfoundland');
insert into `timezone_master` (`id`, `name`, `code`) values('2020','Brasilia','Brazil/East');
insert into `timezone_master` (`id`, `name`, `code`) values('2021','Buenos Aires','America/Buenos_Aires');
insert into `timezone_master` (`id`, `name`, `code`) values('2022','Greenland','America/Godthab');
insert into `timezone_master` (`id`, `name`, `code`) values('2023','Mid-Atlantic','Canada/Atlantic');
insert into `timezone_master` (`id`, `name`, `code`) values('2024','Azores','Atlantic/Azores');
insert into `timezone_master` (`id`, `name`, `code`) values('2025','Cape Verde Is.','Atlantic/Cape_Verde');
insert into `timezone_master` (`id`, `name`, `code`) values('2026','Casablanca, Monrovia','Africa/Casablanca');
insert into `timezone_master` (`id`, `name`, `code`) values('2027','Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London','Europe/Dublin');
insert into `timezone_master` (`id`, `name`, `code`) values('2028','Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna','Europe/Amsterdam');
insert into `timezone_master` (`id`, `name`, `code`) values('2029','Belgrade, Bratislava, Budapest, Ljubljana, Prague','Europe/Belgrade');
insert into `timezone_master` (`id`, `name`, `code`) values('2030','Brussels, Copenhagen, Madrid, Paris','Europe/Brussels');
insert into `timezone_master` (`id`, `name`, `code`) values('2031','Sarajevo, Skopje, Warsaw, Zagreb','Europe/Sarajevo');
insert into `timezone_master` (`id`, `name`, `code`) values('2032','West Central Africa','Europe/Athens');
insert into `timezone_master` (`id`, `name`, `code`) values('2033','Athens, Beirut, Istanbul, Minsk','Europe/Athens');
insert into `timezone_master` (`id`, `name`, `code`) values('2034','Bucharest','Europe/Bucharest');
insert into `timezone_master` (`id`, `name`, `code`) values('2035','Cairo','Africa/Cairo');
insert into `timezone_master` (`id`, `name`, `code`) values('2036','Harare, Pretoria','Africa/Harare');
insert into `timezone_master` (`id`, `name`, `code`) values('2037','Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius','Europe/Helsinki');
insert into `timezone_master` (`id`, `name`, `code`) values('2038','Jerusalem','Asia/Jerusalem');
insert into `timezone_master` (`id`, `name`, `code`) values('2039','Baghdad','Asia/Baghdad');
insert into `timezone_master` (`id`, `name`, `code`) values('2040','Kuwait, Riyadh','Asia/Kuwait');
insert into `timezone_master` (`id`, `name`, `code`) values('2041','Moscow, St. Petersburg, Volgograd','Europe/Moscow');
insert into `timezone_master` (`id`, `name`, `code`) values('2042','Nairobi','Africa/Nairobi');
insert into `timezone_master` (`id`, `name`, `code`) values('2043','Tehran','Asia/Tehran');
insert into `timezone_master` (`id`, `name`, `code`) values('2044','Abu Dhabi, Muscat','Asia/Muscat');
insert into `timezone_master` (`id`, `name`, `code`) values('2045','Baku, Tbilisi, Yerevan','Asia/Baku');
insert into `timezone_master` (`id`, `name`, `code`) values('2046','Kabul','Asia/Kabul');
insert into `timezone_master` (`id`, `name`, `code`) values('2047','Ekaterinburg','Asia/Yekaterinburg');
insert into `timezone_master` (`id`, `name`, `code`) values('2048','Islamabad, Karachi, Tashkent','Asia/Karachi');
insert into `timezone_master` (`id`, `name`, `code`) values('2049','Chennai, Kolkata, Mumbai, New Delhi','Asia/Kolkata');
insert into `timezone_master` (`id`, `name`, `code`) values('2050','Kathmandu','Asia/Kathmandu');
insert into `timezone_master` (`id`, `name`, `code`) values('2051','Almaty, Novosibirsk','Asia/Almaty');
insert into `timezone_master` (`id`, `name`, `code`) values('2052','Astana, Dhaka','Asia/Dhaka');
insert into `timezone_master` (`id`, `name`, `code`) values('2053','Sri Jayawardenepura','Asia/Kolkata');
insert into `timezone_master` (`id`, `name`, `code`) values('2054','Rangoon','Asia/Rangoon');
insert into `timezone_master` (`id`, `name`, `code`) values('2055','Bangkok, Hanoi, Jakarta','Asia/Bangkok');
insert into `timezone_master` (`id`, `name`, `code`) values('2056','Krasnoyarsk','Asia/Krasnoyarsk');
insert into `timezone_master` (`id`, `name`, `code`) values('2057','Beijing, Chongqing, Hong Kong, Urumqi','Asia/Chongqing');
insert into `timezone_master` (`id`, `name`, `code`) values('2058','Irkutsk, Ulaan Bataar','Asia/Irkutsk');
insert into `timezone_master` (`id`, `name`, `code`) values('2059','Kuala Lumpur, Singapore','Asia/Kuala_Lumpur');
insert into `timezone_master` (`id`, `name`, `code`) values('2060','Perth','Australia/Perth');
insert into `timezone_master` (`id`, `name`, `code`) values('2061','Taipei','Asia/Taipei');
insert into `timezone_master` (`id`, `name`, `code`) values('2062','Osaka, Sapporo, Tokyo','Asia/Tokyo');
insert into `timezone_master` (`id`, `name`, `code`) values('2063','Seoul','Asia/Seoul');
insert into `timezone_master` (`id`, `name`, `code`) values('2064','Yakutsk','Asia/Yakutsk');
insert into `timezone_master` (`id`, `name`, `code`) values('2065','Adelaide','Australia/Adelaide');
insert into `timezone_master` (`id`, `name`, `code`) values('2066','Darwin','Australia/Darwin');
insert into `timezone_master` (`id`, `name`, `code`) values('2067','Brisbane','Australia/Brisbane');
insert into `timezone_master` (`id`, `name`, `code`) values('2068','Canberra, Melbourne, Sydney','Australia/Canberra');
insert into `timezone_master` (`id`, `name`, `code`) values('2069','Guam, Port Moresby','Pacific/Guam');
insert into `timezone_master` (`id`, `name`, `code`) values('2070','Hobart','Australia/Hobart');
insert into `timezone_master` (`id`, `name`, `code`) values('2071','Vladivostok','Asia/Vladivostok');
insert into `timezone_master` (`id`, `name`, `code`) values('2072','Magadan, Solomon Is., New Caledonia','Asia/Magadan');
insert into `timezone_master` (`id`, `name`, `code`) values('2073','Auckland, Wellington','Pacific/Auckland');
insert into `timezone_master` (`id`, `name`, `code`) values('2074','Fiji, Kamchatka, Marshall Is.','Pacific/Fiji');
insert into `timezone_master` (`id`, `name`, `code`) values('2075','Nuku\'alofa','Pacific/Tongatapu');
insert into `timezone_master` (`id`, `name`, `code`) values('2076','Georgetown','America/Guyana');